apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-paper-scissors
  labels:
    app: rock-paper-scissors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rock-paper-scissors
  template:
    metadata:
      labels:
        app: rock-paper-scissors
    spec:
      containers:
        - name: rock-paper-scissors
          image: ghcr.io/restfulayush/rock-paper-scissors:sha-62eeee6570aee8251faa8f5bb6e1f35cb926172b
          # Image will be automatically updated by CI/CD pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry
